# Generated by Django 4.2.7 on 2026-02-07 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=50, unique=True, verbose_name='Konteyner ID')),
                ('container_type', models.CharField(choices=[('organic', 'Organik'), ('paper', 'Kağıt'), ('plastic', 'Plastik'), ('glass', 'Cam'), ('metal', 'Metal'), ('general', 'Genel')], max_length=20, verbose_name='Konteyner Tipi')),
                ('capacity', models.IntegerField(default=100, verbose_name='Kapasite (Litre)')),
                ('fill_level', models.IntegerField(default=0, verbose_name='Doluluk Seviyesi (%)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Enlem')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Boylam')),
                ('address', models.CharField(max_length=255, verbose_name='Adres')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Mahalle')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('maintenance', 'Bakımda'), ('damaged', 'Arızalı'), ('inactive', 'Pasif')], default='active', max_length=20, verbose_name='Durum')),
                ('last_emptied', models.DateTimeField(blank=True, null=True, verbose_name='Son Boşaltma')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sıcaklık (°C)')),
                ('battery_level', models.IntegerField(default=100, verbose_name='Batarya (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Konteyner',
                'verbose_name_plural': 'Konteynerler',
                'ordering': ['-fill_level'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Belediye Adı')),
                ('city', models.CharField(max_length=50, verbose_name='İl')),
                ('district', models.CharField(max_length=50, verbose_name='İlçe')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('center_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Merkez Enlem')),
                ('center_lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Merkez Boylam')),
                ('alert_threshold', models.IntegerField(default=80, verbose_name='Uyarı Eşiği (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Belediye',
                'verbose_name_plural': 'Belediyeler',
            },
        ),
        migrations.CreateModel(
            name='CollectionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100, verbose_name='Rota Adı')),
                ('vehicle_plate', models.CharField(max_length=20, verbose_name='Araç Plakası')),
                ('scheduled_date', models.DateTimeField(verbose_name='Planlanan Tarih')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('total_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Toplam Mesafe (km)')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('containers', models.ManyToManyField(to='core.container', verbose_name='Konteynerler')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sürücü')),
            ],
            options={
                'verbose_name': 'Toplama Rotası',
                'verbose_name_plural': 'Toplama Rotaları',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('full', 'Konteyner Dolu'), ('maintenance', 'Bakım Gerekli'), ('damage', 'Arıza'), ('battery', 'Düşük Batarya'), ('temperature', 'Yüksek Sıcaklık'), ('offline', 'Bağlantı Kesildi')], max_length=20, verbose_name='Uyarı Tipi')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], max_length=20, verbose_name='Öncelik')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Çözüldü')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Çözülme Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.container', verbose_name='Konteyner')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Çözen Kişi')),
            ],
            options={
                'verbose_name': 'Uyarı',
                'verbose_name_plural': 'Uyarılar',
                'ordering': ['-created_at'],
            },
        ),
    ]
