# Generated by Django 4.2.7 on 2026-02-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tutar')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Satış',
                'verbose_name_plural': 'Satışlar',
                'ordering': ['-date'],
            },
        ),
    ]
