# Generated by Django 4.2.7 on 2026-02-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_sale_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='report_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bildirim tipi'),
        ),
    ]
