# Generated by Django 4.2.7 on 2026-02-16 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_container_report_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
